# Generated by Django 5.0.7 on 2024-07-16 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.presentacion')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.ventas')),
            ],
        ),
    ]
