# Generated by Django 5.0.7 on 2024-07-16 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_hola'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hola',
            new_name='Tambo',
        ),
    ]
