# Generated by Django 5.0.7 on 2024-07-17 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_hola_tambo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='producto',
            new_name='producto_provedor',
        ),
        migrations.RemoveField(
            model_name='marca',
            name='logo_Tipo',
        ),
        migrations.AddField(
            model_name='marca',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='marca',
            name='codigo',
            field=models.CharField(default='default_codigo', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='ventas',
            field=models.ManyToManyField(related_name='presentaciones', through='inventario.PresentacionHasVentas', to='inventario.ventas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='compras',
            field=models.ManyToManyField(related_name='productos', through='inventario.ProductoHasCompra', to='inventario.compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedores',
            field=models.ManyToManyField(related_name='productos', through='inventario.ProductoHasProveedor', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='marca',
            name='nombre',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='presentacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='presentacionhasventas',
            name='presentacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_ventas', to='inventario.presentacion'),
        ),
        migrations.AlterField(
            model_name='presentacionhasventas',
            name='ventas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentacion_ventas', to='inventario.ventas'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='productohascompra',
            name='compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_compras', to='inventario.compra'),
        ),
        migrations.AlterField(
            model_name='productohascompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_compras', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='productohasproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_proveedores', to='inventario.producto'),
        ),
        migrations.AlterField(
            model_name='productohasproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_proveedores', to='inventario.proveedor'),
        ),
        migrations.AlterField(
            model_name='ventas',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='inventario.usuario'),
        ),
        migrations.DeleteModel(
            name='Tambo',
        ),
        migrations.AddField(
            model_name='marca',
            name='logo_tipo',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
