# Generated by Django 5.0.6 on 2024-07-17 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_rename_hola_tambo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='cantidad_producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='descripcion_producto',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='fecha_compra',
        ),
        migrations.AddField(
            model_name='compra',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='precio_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
